# -*- coding: utf-8 -*-
"""Copy of bitcoin sentiment analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xkA7rdHrF9bCxhRZOi-HGvsJ5bz-QTNJ

# IMPORT THE LIBRARIES

---
"""

import numpy as np
import pandas as pd
import re
import matplotlib.pyplot as plt
from textblob import TextBlob

"""# IMPORT DATASET"""

from google.colab import files
uploaded = files.upload()

"""# IMPORT THE DATA"""

df = pd.read_csv('Bitcoin_tweets.csv')
df.head()

"""# REMOVE NAN VALUE ROW IN HASHTAG COLUMN"""

df. dropna(subset = ["hashtags"], inplace=True)
df.head(5)

"""# TOTAL VALUE SIZE"""

print("Tweet Size: ", len(df))

"""# GET ONLY TEXTS"""

df = df[['text']]
df.columns = ['tweets']

"""# CREATE A FUNCTION TO CLEAN THE TWEETS"""

def cleanTwt(twt):
    twt = re.sub("#bitcoin", 'bitcoin', twt)
    twt = re.sub("#Bitcoin", 'Bitcoin', twt)
    twt = re.sub('#[A-Za-z0-9]+', '', twt)
    twt = re.sub('\\n', '', twt)
    twt = re.sub('https:\/\/\S+', '', twt)
    return twt

df['cleaned_tweets'] = df['tweets'].apply(cleanTwt)
df

"""# CREATE FUNCTION TO GET SUNJECTIVITY AND POLARITY"""

def getSubjectivity(twt):
    return TextBlob(twt).sentiment.subjectivity

def getPolarity(twt):
    return TextBlob(twt).sentiment.polarity

df['subjectivity'] = df['cleaned_tweets'].apply(getSubjectivity)
df['polarity'] = df['cleaned_tweets'].apply(getPolarity)

df.head(5)

"""# CREATE A FUNCTION TO GET SENTIMENT TEXT"""

def getSentiment(score):
    if score < 0:
        return "negative"
    elif score == 0:
        return "neutral"
    else:
        return "positive"

"""# CREATE A COLUMN TO STORE THE TEXT SENTIMENT"""

df['sentiment'] = df['polarity'].apply(getSentiment)


df.head()

"""# CREATE A SCATTER PLOT TO SHOW SUBJECTIVITY AND POLARITY






"""

plt.figure(figsize=(14,10))

for i in range(0, 2000):
    plt.scatter(df["polarity"].iloc[[i]].values[0], df["subjectivity"].iloc[[i]].values[0], color="Purple")

plt.title("Sentiment Analysis Scatter Plot")
plt.xlabel('polarity')
plt.ylabel('subjectivity')
plt.show()

"""CREATE A BAR CHART TO SHOW THE COUT OF POSITIVE, NEUTRAL AND NEGATIVE SENTIMENTS"""

df['sentiment'].value_counts().plot(kind="bar")
plt.title("Sentiment Analysis Scatter Plot")
plt.xlabel("Polarity")
plt.ylabel("Subjectivity")
plt.show()

